# See this at https://memorynotfound.com/spring-ldap-spring-boot-embedded-ldap-configuration-example/

spring:
  ldap:
    urls: <ldap-url>
    base: <ldap-base-dn>
    username: <ldap-manager-user>
    password: <ldap-password>

    # Embedded Spring LDAP
    
    #embedded:
    #  base-dn: dc=memorynotfound,dc=com
    #  credential:
    #    username: uid=admin
    #    password: secret
    #  ldif: classpath:schema.ldif
    #  port: 12345
    #  validation:
    #    enabled: false
    
    
logging: 
  level: 
    root: DEBUG
    org: 
      springframework: DEBUG
      springframework.security: DEBUG
      springframework.web: DEBUG
      hibernate: INFO